### ISSUE TITLE
Vinosoft organization

### ISSUE THREAD

**Issue by Sylvain** [ksvinothmca/test-proj#1]
Hi!

I'm sorry to use this kind of communication, I didn't know how to reach you. I just wanted to know if you were using the vinosoft organization name on Github? Otherwise, I'd love to get it as it is the name of a product will be releasing soon (with an API gem). 

Again, sorry for disturbing you!

Many thanks.

Sylvain

**Comment by Sylvain** [comment]
Hi @ksvinothmca, have you received my message? If you want to keep Vinosoft org, no worries, just let me know ;) Kind regards

**Comment by ksvinothmca** [comment]
Hi  @Sylvain 
vinosoft name of future software company
